services:
  mk-site:
    container_name: mk-site
    build:
      context: ./market-app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./market-app:/var/www
    depends_on:
      - mk-database
    networks:
      - mk-network

  mk-database:
    container_name: mk-database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-freshmarketpwd}
      MYSQL_PASSWORD: ${DB_PASSWORD-freshmarketpwd}
      MYSQL_USER: ${DB_USERNAME-freshmarket}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mk-network

  # Nginx web server
  nginx:
    image: nginx:stable
    container_name: market-site
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./market-app:/var/www
      - ./utils/docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mk-site
    networks:
      - mk-network

  redis:
    image: redis:latest
    networks:
      - mk-network

volumes:
  dbdata:

networks:
  mk-network:
    driver: bridge